const String API_URL = "CHANGE ME";

const String PREF_KEY_USER_HAS_COMPLETED_ONBOARDING =
    'PREF_KEY_USER_HAS_COMPLETED_ONBOARDING';
const String API_TOKEN = "USER_API_KEY";
const String KEY_SAVED_AT = "SAVED_AT";
